In [1]:
%load_ext dotenv

In [2]:
%dotenv

In [3]:
from arcgis.gis import GIS
import dotenv
import os
import pandas as pd
from traffic_safety.utils import combine_yearly_hotspots, list_feature_classes, summarize_hotspot_bins, generate_hotspots_renderer

In [4]:
home_portal = GIS("home")

In [5]:
gdb_path = os.getenv("HOTSPOT_GDB")
feature_classes = list_feature_classes(gdb_path)
feature_classes

['Traffic_Accidents_2019_Projected_HotSpots',
 'Traffic_Accidents_2020_Projected_HotSpots',
 'Traffic_Accidents_2021_Projected_HotSpots',
 'Traffic_Accidents_2022_Projected_HotSpots',
 'Traffic_Accidents_2023_Projected_HotSpots',
 'Traffic_Accidents_2024_Projected_HotSpots',
 'Traffic_Projected_HotSpots']

In [6]:
base_feature_class = feature_classes[0]
combined_df: pd.DataFrame = combine_yearly_hotspots(gdb_path, base_feature_class)
summarized_df: pd.DataFrame = summarize_hotspot_bins(combined_df, min_years_observed=len(feature_classes))
summarized_df

,OBJECTID,value,GiZScore,GiPValue,Gi_Bin,SHAPE,Gi_Bin_Traffic_Accidents_2019_Projected_HotSpots,Gi_Bin_Traffic_Accidents_2020_Projected_HotSpots,Gi_Bin_Traffic_Accidents_2021_Projected_HotSpots,Gi_Bin_Traffic_Accidents_2022_Projected_HotSpots,Gi_Bin_Traffic_Accidents_2023_Projected_HotSpots,Gi_Bin_Traffic_Accidents_2024_Projected_HotSpots,Gi_Bin_Traffic_Projected_HotSpots,Gi_Bin_median,Gi_Bin_years_observed,Gi_Bin_min,Gi_Bin_max
268,269,3.0,-0.025293,0.979821,-0.0,"{""rings"": [[[950283.7008999996, 6466434.863600...",-0.0,0.0,-0.0,0.0,-0.0,3.0,-0.0,-0.0,7,-0.0,3.0
271,272,4.0,1.078478,0.280821,0.0,"{""rings"": [[[950433.7008999996, 6464034.863600...",0.0,0.0,-0.0,0.0,-0.0,0.0,1.0,0.0,7,0.0,1.0
274,275,1.0,-1.387489,0.165293,-0.0,"{""rings"": [[[950433.7008999996, 6465684.863600...",-0.0,0.0,-0.0,0.0,3.0,0.0,-1.0,0.0,7,-1.0,3.0
282,283,2.0,2.135321,0.032735,2.0,"{""rings"": [[[950583.7008999996, 6463734.863600...",2.0,0.0,-0.0,0.0,-0.0,0.0,2.0,0.0,7,0.0,2.0
338,339,4.0,0.933584,0.350518,0.0,"{""rings"": [[[951483.7008999996, 6463884.863600...",0.0,0.0,-0.0,0.0,-0.0,0.0,1.0,0.0,7,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2200,2201,1.0,0.208514,0.834828,0.0,"{""rings"": [[[972933.7008999996, 6467484.863600...",0.0,0.0,-0.0,0.0,-0.0,3.0,-0.0,0.0,7,0.0,3.0
2202,2203,1.0,-0.561104,0.574727,-0.0,"{""rings"": [[[972933.7008999996, 6469284.863600...",-0.0,0.0,-0.0,0.0,-0.0,0.0,-0.0,0.0,7,-0.0,-0.0
2258,2259,1.0,0.093106,0.925819,0.0,"{""rings"": [[[973533.7008999996, 6473934.863600...",0.0,0.0,-0.0,0.0,-0.0,0.0,-0.0,0.0,7,0.0,0.0
2277,2278,2.0,0.093106,0.925819,0.0,"{""rings"": [[[973833.7008999996, 6473034.863600...",0.0,0.0,-0.0,0.0,-0.0,0.0,-0.0,0.0,7,0.0,0.0
2330,2331,1.0,-0.653183,0.513638,-0.0,"{""rings"": [[[974433.7008999996, 6467034.863600...",-0.0,2.0,3.0,0.0,-0.0,0.0,-1.0,0.0,7,-1.0,3.0

In [7]:
hottest_df = summarized_df[summarized_df["Gi_Bin_median"].between(2, 3)]
hottest_df.sort_values(by="Gi_Bin_median", ascending=False).head()

,OBJECTID,value,GiZScore,GiPValue,Gi_Bin,SHAPE,Gi_Bin_Traffic_Accidents_2019_Projected_HotSpots,Gi_Bin_Traffic_Accidents_2020_Projected_HotSpots,Gi_Bin_Traffic_Accidents_2021_Projected_HotSpots,Gi_Bin_Traffic_Accidents_2022_Projected_HotSpots,Gi_Bin_Traffic_Accidents_2023_Projected_HotSpots,Gi_Bin_Traffic_Accidents_2024_Projected_HotSpots,Gi_Bin_Traffic_Projected_HotSpots,Gi_Bin_median,Gi_Bin_years_observed,Gi_Bin_min,Gi_Bin_max
957,958,2.0,3.281122,0.001034,3.0,"{""rings"": [[[961233.7008999996, 6463884.863600...",3.0,1.0,3.0,3.0,-0.0,0.0,3.0,3.0,7,-0.0,3.0
1188,1189,6.0,4.553996,0.000005,3.0,"{""rings"": [[[963183.7008999996, 6464634.863600...",3.0,3.0,3.0,0.0,3.0,3.0,3.0,3.0,7,0.0,3.0
1168,1169,3.0,4.601287,0.000004,3.0,"{""rings"": [[[963033.7008999996, 6464634.863600...",3.0,3.0,3.0,0.0,3.0,3.0,3.0,3.0,7,0.0,3.0
1223,1224,7.0,3.074181,0.002111,3.0,"{""rings"": [[[963483.7008999996, 6464784.863600...",3.0,1.0,3.0,0.0,3.0,3.0,3.0,3.0,7,0.0,3.0
1280,1281,5.0,4.771831,0.000002,3.0,"{""rings"": [[[964083.7008999996, 6465234.863600...",3.0,0.0,3.0,3.0,3.0,2.0,3.0,3.0,7,0.0,3.0

In [8]:
map_view = home_portal.map()
map_view.basemap.basemap = "osm"
drawing_info = { 
    "renderer": generate_hotspots_renderer(field_name="Gi_Bin_median")
}
hottest_fset = hottest_df.copy().spatial.to_featureset()
map_view.content.add(hottest_fset, drawing_info=drawing_info, options={"opacity": 0.7})
map_view.zoom_to_layer(hottest_fset)
map_view

Map()